#include "tls/b9c_stream.h"
#include <string.h>
namespace it360_tls {
namespace {
static WORD R16(const BYTE* p){return static_cast<WORD>((static_cast<unsigned>(p[0])<<8)|p[1]);}
static DWORD R32(const BYTE* p){return (static_cast<DWORD>(p[0])<<24)|(static_cast<DWORD>(p[1])<<16)|(static_cast<DWORD>(p[2])<<8)|p[3];}
static void W16(BYTE* p,WORD v){p[0]=static_cast<BYTE>(v>>8);p[1]=static_cast<BYTE>(v);}
static void W32(BYTE* p,DWORD v){p[0]=static_cast<BYTE>(v>>24);p[1]=static_cast<BYTE>(v>>16);p[2]=static_cast<BYTE>(v>>8);p[3]=static_cast<BYTE>(v);}
static unsigned long Sum(const BYTE* p,unsigned n,unsigned long s){while(n>=2){s+=((unsigned)p[0]<<8)|p[1];p+=2;n-=2;}if(n)s+=(unsigned)p[0]<<8;while(s>>16)s=(s&0xffffu)+(s>>16);return s;}
static WORD Finish(unsigned long s){while(s>>16)s=(s&0xffffu)+(s>>16);return static_cast<WORD>(~s&0xffffu);}
static WORD Checksum(const BYTE* p,unsigned n){return Finish(Sum(p,n,0));}
static WORD Transport(DWORD src,DWORD dst,BYTE proto,const BYTE* p,unsigned n){BYTE q[12];W32(q,src);W32(q+4,dst);q[8]=0;q[9]=proto;W16(q+10,(WORD)n);WORD c=Finish(Sum(p,n,Sum(q,12,0)));return c?c:(WORD)0xffff;}
static unsigned SkipName(const BYTE* p,unsigned n,unsigned o){unsigned guard=0;while(o<n&&guard++<128){BYTE c=p[o];if(!c)return o+1;if((c&0xc0)==0xc0)return o+2<=n?o+2:0;if(c>63||o+1u+c>n)return 0;o+=1u+c;}return 0;}
static bool MacEq(const BYTE* a,const BYTE* b){return memcmp(a,b,6)==0;}
}
B9cTcpStream::B9cTcpStream(){Reset();}
void B9cTcpStream::Reset(){memset(&cfg_,0,sizeof(cfg_));memset(gateway_mac_,0,6);send_=0;send_user_=0;remote_ip_=0;remote_port_=0;local_port_=0;dns_id_=0;ip_id_=1;send_seq_=0;recv_seq_=0;peer_ack_=0;resolved_ip_=0;configured_=dns_done_=connected_=closed_=failed_=rx_lock_=0;rx_head_=rx_tail_=rx_count_=0;}
bool B9cTcpStream::Configure(const it360_net::NetConfig& config,const BYTE gateway_mac[6],it360_net::FrameSendFn send,void* user){Reset();if(!gateway_mac||!send||!config.ip||!config.dns)return false;cfg_=config;memcpy(gateway_mac_,gateway_mac,6);send_=send;send_user_=user;const DWORD mix=cfg_.ip^cfg_.gateway^static_cast<DWORD>(it360_platform::MonotonicMs());dns_id_=(WORD)((mix^(mix>>16))&0xffffu);if(!dns_id_)dns_id_=0x4936;local_port_=(WORD)(50000u+(mix&0x0fffu));send_seq_=0x36000000u|(mix&0x00ffffffu);it360_platform::AtomicExchange(&configured_,1);return true;}
void B9cTcpStream::Fail(){it360_platform::AtomicExchange(&failed_,1);it360_platform::AtomicExchange(&connected_,0);}
bool B9cTcpStream::SendIpv4Raw(DWORD dst,BYTE proto,const BYTE* payload,unsigned len){if(!send_||len>1480)return false;BYTE frame[1514];memcpy(frame,gateway_mac_,6);memcpy(frame+6,cfg_.mac,6);W16(frame+12,0x0800);BYTE* ip=frame+14;memset(ip,0,20);ip[0]=0x45;W16(ip+2,(WORD)(20+len));W16(ip+4,ip_id_++);W16(ip+6,0x4000);ip[8]=64;ip[9]=proto;W32(ip+12,cfg_.ip);W32(ip+16,dst);W16(ip+10,Checksum(ip,20));if(len)memcpy(ip+20,payload,len);return send_(frame,14+20+len,send_user_);}
bool B9cTcpStream::SendIpv4Udp(DWORD dst,WORD sp,WORD dp,const BYTE* payload,unsigned len){if(len>1400)return false;BYTE udp[1408];W16(udp,sp);W16(udp+2,dp);W16(udp+4,(WORD)(8+len));W16(udp+6,0);if(len)memcpy(udp+8,payload,len);W16(udp+6,Transport(cfg_.ip,dst,17,udp,8+len));return SendIpv4Raw(dst,17,udp,8+len);}
bool B9cTcpStream::SendDnsQuery(const char* host){if(!host||!host[0])return false;BYTE q[512];memset(q,0,sizeof(q));W16(q,dns_id_);W16(q+2,0x0100);W16(q+4,1);unsigned o=12,start=0,n=(unsigned)strlen(host);while(start<n){unsigned end=start;while(end<n&&host[end]!='.')++end;unsigned l=end-start;if(!l||l>63||o+1+l+5>sizeof(q))return false;q[o++]=(BYTE)l;memcpy(q+o,host+start,l);o+=l;start=end+1;}q[o++]=0;W16(q+o,1);o+=2;W16(q+o,1);o+=2;return SendIpv4Udp(cfg_.dns,(WORD)(54000u+(dns_id_&0x03ffu)),53,q,o);}
bool B9cTcpStream::ResolveHost(const char* host,DWORD* address,const Deadline& deadline){if(!address||it360_platform::AtomicCompareExchange(&configured_,0,0)==0)return false;*address=0;it360_platform::AtomicExchange(&dns_done_,0);resolved_ip_=0;if(!SendDnsQuery(host))return false;while(!deadline.Expired()){if(it360_platform::AtomicCompareExchange(&failed_,0,0))return false;if(it360_platform::AtomicCompareExchange(&dns_done_,0,0)){*address=resolved_ip_;return *address!=0;}it360_platform::SleepMs(5);}return false;}
bool B9cTcpStream::SendTcp(BYTE flags,const BYTE* payload,unsigned len,DWORD seq){if(!remote_ip_||!remote_port_||len>1360)return false;BYTE tcp[1380];memset(tcp,0,20);W16(tcp,local_port_);W16(tcp+2,remote_port_);W32(tcp+4,seq);W32(tcp+8,recv_seq_);tcp[12]=5u<<4;tcp[13]=flags;W16(tcp+14,32768);if(len)memcpy(tcp+20,payload,len);W16(tcp+16,Transport(cfg_.ip,remote_ip_,6,tcp,20+len));return SendIpv4Raw(remote_ip_,6,tcp,20+len);}
bool B9cTcpStream::Connect(DWORD address,WORD port,const Deadline& deadline){if(!address||!port||it360_platform::AtomicCompareExchange(&configured_,0,0)==0)return false;remote_ip_=address;remote_port_=port;recv_seq_=0;peer_ack_=0;closed_=0;failed_=0;connected_=0;const DWORD syn=send_seq_;if(!SendTcp(0x02,0,0,syn))return false;send_seq_=syn+1u;while(!deadline.Expired()){if(it360_platform::AtomicCompareExchange(&failed_,0,0))return false;if(it360_platform::AtomicCompareExchange(&connected_,0,0))return true;it360_platform::SleepMs(5);}return false;}
bool B9cTcpStream::PushRx(const BYTE* data,unsigned len){if(!data||!len)return true;if(it360_platform::AtomicCompareExchange(&rx_lock_,1,0)!=0)return false;if(len>sizeof(rx_)-rx_count_){it360_platform::AtomicExchange(&rx_lock_,0);return false;}for(unsigned i=0;i<len;++i){rx_[rx_tail_]=data[i];rx_tail_=(rx_tail_+1u)%sizeof(rx_);}rx_count_+=len;it360_platform::AtomicExchange(&rx_lock_,0);return true;}
unsigned B9cTcpStream::PopRx(BYTE* data,unsigned cap){if(!data||!cap||it360_platform::AtomicCompareExchange(&rx_lock_,1,0)!=0)return 0;unsigned n=rx_count_<cap?rx_count_:cap;for(unsigned i=0;i<n;++i){data[i]=rx_[rx_head_];rx_head_=(rx_head_+1u)%sizeof(rx_);}rx_count_-=n;it360_platform::AtomicExchange(&rx_lock_,0);return n;}
int B9cTcpStream::Read(void* data,unsigned cap,const Deadline& deadline){if(!data||!cap)return -1;while(!deadline.Expired()){unsigned n=PopRx(static_cast<BYTE*>(data),cap);if(n)return (int)n;if(it360_platform::AtomicCompareExchange(&failed_,0,0))return -1;if(it360_platform::AtomicCompareExchange(&closed_,0,0))return 0;it360_platform::SleepMs(2);}return -1;}
int B9cTcpStream::Write(const void* data,unsigned len,const Deadline& deadline){if(!data&&len)return -1;if(!it360_platform::AtomicCompareExchange(&connected_,0,0))return -1;const BYTE* p=static_cast<const BYTE*>(data);unsigned done=0;while(done<len&&!deadline.Expired()){unsigned chunk=len-done;if(chunk>1200)chunk=1200;const DWORD seq=send_seq_;if(!SendTcp(0x18,p+done,chunk,seq)){Fail();return -1;}send_seq_+=chunk;done+=chunk;while(!deadline.Expired()&&peer_ack_<send_seq_&&!it360_platform::AtomicCompareExchange(&failed_,0,0))it360_platform::SleepMs(1);if(peer_ack_<send_seq_&&deadline.Expired())return -1;}return (int)done;}
bool B9cTcpStream::OnEthernetFrame(const BYTE* frame,unsigned length){if(!frame||length<34||it360_platform::AtomicCompareExchange(&configured_,0,0)==0)return true;if(!MacEq(frame,cfg_.mac)&&!(frame[0]&1u))return true;if(R16(frame+12)!=0x0800)return true;const BYTE* ip=frame+14;unsigned n=length-14;if(n<20||(ip[0]>>4)!=4)return true;unsigned ihl=(ip[0]&0x0f)*4;if(ihl<20||ihl>n)return true;unsigned total=R16(ip+2);if(total<ihl||total>n)return true;DWORD src=R32(ip+12),dst=R32(ip+16);if(dst!=cfg_.ip)return true;const BYTE* body=ip+ihl;unsigned blen=total-ihl;if(ip[9]==17&&src==cfg_.dns&&blen>=8){WORD dp=R16(body+2);if(dp!=(WORD)(54000u+(dns_id_&0x03ffu)))return true;unsigned ulen=R16(body+4);if(ulen<8||ulen>blen)return true;const BYTE* d=body+8;unsigned dn=ulen-8;if(dn<12||R16(d)!=dns_id_||(R16(d+2)&0x8000)==0)return true;unsigned o=12,qd=R16(d+4),an=R16(d+6);for(unsigned i=0;i<qd;++i){o=SkipName(d,dn,o);if(!o||o+4>dn)return true;o+=4;}for(unsigned i=0;i<an;++i){o=SkipName(d,dn,o);if(!o||o+10>dn)return true;WORD type=R16(d+o),klass=R16(d+o+2),rdlen=R16(d+o+8);o+=10;if(o+rdlen>dn)return true;if(type==1&&klass==1&&rdlen==4){resolved_ip_=R32(d+o);it360_platform::AtomicExchange(&dns_done_,1);return true;}o+=rdlen;}it360_platform::AtomicExchange(&dns_done_,1);return true;}if(ip[9]!=6||src!=remote_ip_||blen<20)return true;if(R16(body)!=remote_port_||R16(body+2)!=local_port_)return true;unsigned thl=(body[12]>>4)*4;if(thl<20||thl>blen)return true;BYTE flags=body[13];DWORD seq=R32(body+4),ack=R32(body+8);unsigned data_len=blen-thl;const BYTE* data=body+thl;if(ack>peer_ack_)peer_ack_=ack;if(!it360_platform::AtomicCompareExchange(&connected_,0,0)){if((flags&0x12)==0x12&&ack==send_seq_){recv_seq_=seq+1u;it360_platform::AtomicExchange(&connected_,1);SendTcp(0x10,0,0,send_seq_);}else if(flags&0x04)Fail();return true;}if(data_len){if(seq==recv_seq_){if(!PushRx(data,data_len)){Fail();return false;}recv_seq_+=data_len;}SendTcp(0x10,0,0,send_seq_);}if(flags&0x01){if(seq+data_len==recv_seq_)++recv_seq_;SendTcp(0x10,0,0,send_seq_);it360_platform::AtomicExchange(&closed_,1);it360_platform::AtomicExchange(&connected_,0);}if(flags&0x04){it360_platform::AtomicExchange(&closed_,1);it360_platform::AtomicExchange(&connected_,0);}return true;}
void B9cTcpStream::Close(){if(it360_platform::AtomicCompareExchange(&connected_,0,0))SendTcp(0x11,0,0,send_seq_);it360_platform::AtomicExchange(&connected_,0);it360_platform::AtomicExchange(&closed_,1);}
bool B9cTcpStream::Connected() const{return it360_platform::AtomicCompareExchange(const_cast<volatile LONG*>(&connected_),0,0)!=0;}
}
